name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v1
        with:
          token: ${{secrets.github_token}}

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: diluv/clamav
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true